### ISSUE TITLE
Failing test: distributions.tests.test_models.test_add_remove('lp.models.niw')

### ISSUE THREAD

**Issue by doctorpangloss** [posterior/loom#4]
See the attached Vagrantfile for the build environment:

[Vagrantfile.txt](https://github.com/posterior/loom/files/1206108/Vagrantfile.txt)

```
======================================================================
FAIL: distributions.tests.test_models.test_add_remove('lp.models.niw',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/distributions/distributions/tests/test_models.py", line 104, in test_one_model
    test_fun(module, EXAMPLE)
  File "/home/vagrant/distributions/distributions/tests/test_models.py", line 246, in test_add_remove
    err_msg='p(x1,...,xn) != p(x1) p(x2|x1) p(xn|...)')
  File "/home/vagrant/distributions/distributions/tests/util.py", line 120, in assert_close
    assert_less(diff, tol * norm, msg)

AssertionError: p(x1,...,xn) != p(x1) p(x2|x1) p(xn|...) off by 0.105773141425% = 0.00499747693539
-------------------- >> begin captured stdout << ---------------------
example 1/4
example 2/4
example 3/4
p(x1,...,xn) != p(x1) p(x2|x1) p(xn|...)
actual = 1.86485503614
expected = 1.8598575592
```

**Comment by fritzo** [comment]
`niw` is known to be buggy. See https://github.com/posterior/distributions/issues/6
